import vk_api
import requests
import json
from vk_api.keyboard import VkKeyboard, VkKeyboardColor
from bs4 import BeautifulSoup


class Tram:

    def __init__(self):
        self.rasp = VkKeyboard(one_time=True)
        self.rasp.add_button('Трамвай', color=VkKeyboardColor.POSITIVE)
        self.rasp.add_button('Троллейбус', color=VkKeyboardColor.POSITIVE)
        self.rasp.add_line()
        self.rasp.add_button('Автобус', color=VkKeyboardColor.PRIMARY)
        self.rasp.add_line()
        self.rasp.add_button('Меню', color=VkKeyboardColor.SECONDARY)

        self.t_k_rasp = VkKeyboard(one_time=True)
        self.t_k_rasp.add_button('Kраснодар', color=VkKeyboardColor.PRIMARY)
        self.t_k_rasp.add_button('Рoстов-На-Дону', color=VkKeyboardColor.PRIMARY)
        self.t_k_rasp.add_line()
        self.t_k_rasp.add_button('Меню', color=VkKeyboardColor.SECONDARY)

        self.t_k_marsh = VkKeyboard(one_time=True)
        self.t_k_marsh.add_button('КТ 1', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_button('КТ 2', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_button('КТ 3', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_button('КТ 4', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_line()
        self.t_k_marsh.add_button('КТ 5', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_button('КТ 6', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_button('КТ 7', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_button('КТ 8', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_line()
        self.t_k_marsh.add_button('КТ 9', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_button('КТ 10', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_button('КТ 11', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_button('КТ 12', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_line()
        self.t_k_marsh.add_button('КТ 15', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_button('КТ 20', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_button('КТ 21', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_button('КТ 22', color=VkKeyboardColor.PRIMARY)
        self.t_k_marsh.add_line()
        self.t_k_marsh.add_button('Вернуть', color=VkKeyboardColor.SECONDARY)
        self.t_k_marsh.add_button('Меню', color=VkKeyboardColor.SECONDARY)

        self.t_k_marsh2 = VkKeyboard(one_time=True)
        self.t_k_marsh2.add_button('Вернуть', color=VkKeyboardColor.SECONDARY)
        self.t_k_marsh2.add_button('Меню', color=VkKeyboardColor.SECONDARY)

        self.tl_k_marsh = VkKeyboard(one_time=True)
        self.tl_k_marsh.add_button('КТЛ 2', color=VkKeyboardColor.PRIMARY)
        self.tl_k_marsh.add_button('КТЛ 4', color=VkKeyboardColor.PRIMARY)
        self.tl_k_marsh.add_button('КТЛ 6', color=VkKeyboardColor.PRIMARY)
        self.tl_k_marsh.add_button('КТЛ 7', color=VkKeyboardColor.PRIMARY)
        self.tl_k_marsh.add_line()
        self.tl_k_marsh.add_button('КТЛ 8', color=VkKeyboardColor.PRIMARY)
        self.tl_k_marsh.add_button('КТЛ 10', color=VkKeyboardColor.PRIMARY)
        self.tl_k_marsh.add_button('КТЛ 12', color=VkKeyboardColor.PRIMARY)
        self.tl_k_marsh.add_button('КТЛ 13', color=VkKeyboardColor.PRIMARY)
        self.tl_k_marsh.add_line()
        self.tl_k_marsh.add_button('КТЛ 14', color=VkKeyboardColor.PRIMARY)
        self.tl_k_marsh.add_button('КТЛ 15', color=VkKeyboardColor.PRIMARY)
        self.tl_k_marsh.add_button('КТЛ 20', color=VkKeyboardColor.PRIMARY)
        self.tl_k_marsh.add_button('КТЛ 21', color=VkKeyboardColor.PRIMARY)
        self.tl_k_marsh.add_line()
        self.tl_k_marsh.add_button('Вернуть', color=VkKeyboardColor.SECONDARY)
        self.tl_k_marsh.add_button('Меню', color=VkKeyboardColor.SECONDARY)

        self.b_k_marsh = VkKeyboard(one_time=True)
        self.b_k_marsh.add_button('АТ 2', color=VkKeyboardColor.PRIMARY)
        self.b_k_marsh.add_button('АТ 2E', color=VkKeyboardColor.PRIMARY)
        self.b_k_marsh.add_button('АТ 4', color=VkKeyboardColor.PRIMARY)
        self.b_k_marsh.add_button('АТ 9', color=VkKeyboardColor.PRIMARY)
        self.b_k_marsh.add_line()
        self.b_k_marsh.add_button('АТ 10', color=VkKeyboardColor.PRIMARY)
        self.b_k_marsh.add_button('АТ 43', color=VkKeyboardColor.PRIMARY)
        self.b_k_marsh.add_button('АТ 46', color=VkKeyboardColor.PRIMARY)
        self.b_k_marsh.add_button('АТ 52', color=VkKeyboardColor.PRIMARY)
        self.b_k_marsh.add_line()
        self.b_k_marsh.add_button('АТ 55', color=VkKeyboardColor.PRIMARY)
        self.b_k_marsh.add_button('АТ 96', color=VkKeyboardColor.PRIMARY)
        self.b_k_marsh.add_line()
        self.b_k_marsh.add_button('Вернуть', color=VkKeyboardColor.SECONDARY)
        self.b_k_marsh.add_button('Меню', color=VkKeyboardColor.SECONDARY)

        # Rostov

        self.raspr = VkKeyboard(one_time=True)
        self.raspr.add_button('Tрамвай', color=VkKeyboardColor.POSITIVE)
        self.raspr.add_button('Tроллейбус', color=VkKeyboardColor.POSITIVE)
        self.raspr.add_line()
        self.raspr.add_button('Aвтобус', color=VkKeyboardColor.PRIMARY)
        self.raspr.add_button('Межгородской', color=VkKeyboardColor.PRIMARY)
        self.raspr.add_line()
        self.raspr.add_button('Меню', color=VkKeyboardColor.SECONDARY)

        self.b_r_marsh = VkKeyboard(one_time=True)
        self.b_r_marsh.add_button('АР 1', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 2', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 2A', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 3', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_line()
        self.b_r_marsh.add_button('АР 3A', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 4', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 6', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 6A', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_line()
        self.b_r_marsh.add_button('АР 7', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 8', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 10', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 11', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_line()
        self.b_r_marsh.add_button('АР 12', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 13', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 14', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 15', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_line()
        self.b_r_marsh.add_button('АР 16', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 16A', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 17', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 18', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_line()
        self.b_r_marsh.add_button('Меню', color=VkKeyboardColor.SECONDARY)
        self.b_r_marsh.add_button('АР 19', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('АР 20', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh.add_button('Дальшe', color=VkKeyboardColor.SECONDARY)

        self.b_r_marsh2 = VkKeyboard(one_time=True)
        self.b_r_marsh2.add_button('АР 21', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 22', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 24', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 25', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_line()
        self.b_r_marsh2.add_button('АР 26', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 27', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 28', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 29', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_line()
        self.b_r_marsh2.add_button('АР 30', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 31', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 32', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 33', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_line()
        self.b_r_marsh2.add_button('АР 34', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 34A', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 34P', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 35', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_line()
        self.b_r_marsh2.add_button('АР 36', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 38', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 39', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 40', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_line()
        self.b_r_marsh2.add_button('Вeрнуть', color=VkKeyboardColor.SECONDARY)
        self.b_r_marsh2.add_button('АР 41', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('АР 42', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh2.add_button('Дaльше', color=VkKeyboardColor.SECONDARY)

        self.b_r_marsh3 = VkKeyboard(one_time=True)
        self.b_r_marsh3.add_button('АР 43', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 44', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 45', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 47', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_line()
        self.b_r_marsh3.add_button('АР 48', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 49', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 50', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 51', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_line()
        self.b_r_marsh3.add_button('АР 54', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 55', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 56', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 57', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_line()
        self.b_r_marsh3.add_button('АР 60', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 60A', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 61', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 63', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_line()
        self.b_r_marsh3.add_button('АР 64', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 65', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 65A', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 66', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_line()
        self.b_r_marsh3.add_button('Bернуть', color=VkKeyboardColor.SECONDARY)
        self.b_r_marsh3.add_button('АР 67', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('АР 67A', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh3.add_button('Вперед', color=VkKeyboardColor.SECONDARY)

        self.b_r_marsh4 = VkKeyboard(one_time=True)
        self.b_r_marsh4.add_button('АР 68', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 70', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 71', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 72', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_line()
        self.b_r_marsh4.add_button('АР 73', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 74', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 75', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 76', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_line()
        self.b_r_marsh4.add_button('АР 77', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 78', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 80', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 81', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_line()
        self.b_r_marsh4.add_button('АР 82', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 83', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 88', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 90', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_line()
        self.b_r_marsh4.add_button('АР 90A', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 92', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 92A', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 93', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_line()
        self.b_r_marsh4.add_button('АР 94', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 96', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_button('АР 99', color=VkKeyboardColor.PRIMARY)
        self.b_r_marsh4.add_line()
        self.b_r_marsh4.add_button('Beрнуть', color=VkKeyboardColor.SECONDARY)
        self.b_r_marsh4.add_button('Меню', color=VkKeyboardColor.SECONDARY)

        self.tl_r_marsh = VkKeyboard(one_time=True)
        self.tl_r_marsh.add_button('ТЛР 1', color=VkKeyboardColor.PRIMARY)
        self.tl_r_marsh.add_button('ТЛР 2', color=VkKeyboardColor.PRIMARY)
        self.tl_r_marsh.add_button('ТЛР 5', color=VkKeyboardColor.PRIMARY)
        self.tl_r_marsh.add_button('ТЛР 6', color=VkKeyboardColor.PRIMARY)
        self.tl_r_marsh.add_line()
        self.tl_r_marsh.add_button('ТЛР 7', color=VkKeyboardColor.PRIMARY)
        self.tl_r_marsh.add_button('ТЛР 8', color=VkKeyboardColor.PRIMARY)
        self.tl_r_marsh.add_button('ТЛР 9', color=VkKeyboardColor.PRIMARY)
        self.tl_r_marsh.add_button('ТЛР 10', color=VkKeyboardColor.PRIMARY)
        self.tl_r_marsh.add_line()
        self.tl_r_marsh.add_button('ТЛР 12', color=VkKeyboardColor.PRIMARY)
        self.tl_r_marsh.add_button('ТЛР 14', color=VkKeyboardColor.PRIMARY)
        self.tl_r_marsh.add_button('ТЛР 22', color=VkKeyboardColor.PRIMARY)
        self.tl_r_marsh.add_line()
        self.tl_r_marsh.add_button('Меню', color=VkKeyboardColor.SECONDARY)

        self.t_r_marsh = VkKeyboard(one_time=True)
        self.t_r_marsh.add_button('ТР 1', color=VkKeyboardColor.PRIMARY)
        self.t_r_marsh.add_button('ТР 4', color=VkKeyboardColor.PRIMARY)
        self.t_r_marsh.add_button('ТР 6', color=VkKeyboardColor.PRIMARY)
        self.t_r_marsh.add_line()
        self.t_r_marsh.add_button('ТР 7', color=VkKeyboardColor.PRIMARY)
        self.t_r_marsh.add_button('ТР 10', color=VkKeyboardColor.PRIMARY)
        self.t_r_marsh.add_line()
        self.t_r_marsh.add_button('Меню', color=VkKeyboardColor.SECONDARY)

        self.no_city_rast = VkKeyboard(one_time=True)
        self.no_city_rast.add_button('МГР 163', color=VkKeyboardColor.PRIMARY)
        self.no_city_rast.add_button('МГР 164', color=VkKeyboardColor.PRIMARY)
        self.no_city_rast.add_button('МГР 240', color=VkKeyboardColor.PRIMARY)
        self.no_city_rast.add_line()
        self.no_city_rast.add_button('МГР 700', color=VkKeyboardColor.PRIMARY)
        self.no_city_rast.add_button('МГР 800', color=VkKeyboardColor.PRIMARY)
        self.no_city_rast.add_line()
        self.no_city_rast.add_button('Меню', color=VkKeyboardColor.SECONDARY)
